# Generated by Django 5.2.15 on 2026-06-24 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('node_type', models.CharField(choices=[('ROOT', 'Root'), ('AREA', 'Area'), ('MODULE', 'Module'), ('FEATURE', 'Feature'), ('SUBSYSTEM', 'Subsystem'), ('SCREEN', 'Screen'), ('TECHNICAL_TOPIC', 'Technical topic'), ('RESEARCH_TOPIC', 'Research topic'), ('DEPLOYMENT_TOPIC', 'Deployment topic'), ('TESTING_TOPIC', 'Testing topic'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('position', models.PositiveIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bitacora.projectnode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='bitacora.project')),
            ],
            options={
                'ordering': ['position', 'title'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('project', 'slug'), name='unique_root_node_slug_per_project'), models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('project', 'parent', 'slug'), name='unique_sibling_node_slug_per_parent'), models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='project_node_cannot_parent_itself')],
            },
        ),
    ]
