# Generated by Django 5.2.15 on 2026-06-24 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_projectnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('document_type', models.CharField(choices=[('THEORY', 'Theory'), ('SPECIFICATION', 'Specification'), ('PSEUDOCODE', 'Pseudocode'), ('CODE_SNIPPET', 'Code snippet'), ('QUESTION', 'Question'), ('TODO_LIST', 'Todo list'), ('DECISION', 'Decision'), ('BUG_NOTE', 'Bug note'), ('DEPLOYMENT_NOTE', 'Deployment note'), ('REFERENCE', 'Reference'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('NEEDS_REVIEW', 'Needs review'), ('RESOLVED', 'Resolved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=20)),
                ('body_markdown', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bitacora.projectnode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bitacora.project')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('node', 'slug'), name='unique_document_slug_per_node')],
            },
        ),
    ]
