# Generated by Django 5.2.15 on 2026-06-24 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0003_nodedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('work_done', models.TextField(blank=True)),
                ('decisions_made', models.TextField(blank=True)),
                ('doubts_opened', models.TextField(blank=True)),
                ('next_actions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='bitacora.project')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSessionDocumentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_session_references', to='bitacora.nodedocument')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_references', to='bitacora.worksession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('work_session', 'document'), name='unique_work_session_document_reference')],
            },
        ),
        migrations.CreateModel(
            name='WorkSessionNodeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_session_references', to='bitacora.projectnode')),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_references', to='bitacora.worksession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('work_session', 'node'), name='unique_work_session_node_reference')],
            },
        ),
    ]
